
/**
 * 业务方传给FaceAISDK 插件基础参数
 */
export type ResultJSON = {
  code: number,         //code 含义参考Readme 
  msg: string,          //消息
  faceID: string,       //1:1 要对比的faceID,你的业务系统定义用户的唯一字符串（手机/身份证）
  similarity:number,    //相似度 
  liveness:number,      //静默活体分数
  faceFeature: string,  //人脸特征值
  faceBase64: string    //人脸图Base64编码 换个含义
}

/**
 * 「1:1人脸识别」录入人脸信息
 * 
 * @param faceID 用户ID
 * @param needShowConfirmDialog 是否需要显示确认框
 * @param callback 结果回调
 */
export type AddFaceBySDKCamera = (
	faceID : string,
	addFacePerformanceMode:number,
	needShowConfirmDialog:boolean,
	callback : (result : ResultJSON) => void) => void
	
	
	
/**
 * 仅仅用于Android 提取人脸图片中的特征值。不建议通过此方式录入人脸
 * 人脸图需要遵守规范：https://i.postimg.cc/RCwNy0kV/add-Face.jpg
 * 
 * @param faceID 用户ID
 * @param base64FaceImage 人脸图Base64编码
 * @param callback 结果回调
 */
export type AddFaceBySDKImage = (
	faceID : string,
	base64FaceImage:string,
	callback : (result : ResultJSON) => void) => void	
	
	
		
	
/**
 * 「1:1人脸识别」校验是否当前用户
 * 
 * @param faceID 用户ID
 * @param threshold 阈值设置，范围限 [0.75,0.95] ,默认0.85
 * @param faceLivenessType  1.动作活体  2.动作+炫彩活体 3.炫彩活体(不能强光环境使用) 4.静默活体(开发完善中)
 * @param motionLivenessTypes  "1,2,3" 动作活体种类用英文","隔开； 1.张张嘴 2.微笑 3.眨眨眼 4.摇头 5.点头
 * @param motionLivenessTimeOut  动作活体超时时间 [3,15]
 * @param motionLivenessSteps    动作活体步骤，1或2 个
 * @param callback 结果回调
 */
export type FaceVerify = (
	faceID : string,
	threshold : number,
	faceLivenessType : number, 
	motionLivenessTypes : string,
	motionLivenessTimeOut : number,
	motionLivenessSteps : number,
	callback : (result : ResultJSON) => void) => void	
	


/**
 * 「活体检测」 动作｜炫彩活体（炫彩活体不要在强光下）
 * 
 * @param faceLivenessType  1.动作活体  2.动作+炫彩活体 3.炫彩活体(不能强光环境使用) 4.静默活体(开发完善中)
 * @param motionLivenessTypes  "1,2,3" 动作活体种类用英文","隔开； 1.张张嘴 2.微笑 3.眨眨眼 4.摇头 5.点头
 * @param motionLivenessTimeOut  动作活体超时时间 [3,22]
 * @param motionLivenessSteps    动作活体步骤，1或2 个
 * @param callback 结果回调
 */
export type LivenessVerify = (
	faceLivenessType : number, 
	motionLivenessTypes : string,
	motionLivenessTimeOut : number,
	motionLivenessSteps : number,
	callback : (result : ResultJSON) => void) => void	
	
	
	
	
//「1:1人脸识别」检测人脸是否存在
export type GetFaceFeature = (
    faceID: string, 
	callback: (result: ResultJSON) => void) => void
	
/**
 * 「1:1人脸识别」同步人脸特征指到SDK，比如用户换设备登陆了，把上次录入到你的业务服务器上的人脸同步就行
 * 
 * @param faceFeature 人脸特征值得长度1024.20251202新版本SDK人脸数据合规处理不在接收人脸图参数
 * @param callback 结果回调
 */
export type InsertFaceFeature = (
    faceID : string,
	faceFeature : string,
	callback : (result : ResultJSON) => void) => void	
	
	
export type ToastMessage = (message : string) => void	
	
	
//「1:1人脸识别」检测人脸是否存在
export type DeleteFaceFeature = (faceID: string) => void
	
// 切换摄像头	
export type SwitchCamera = (cameraID: number) => void

// 切到原生App
export type GoNativeApp = () => void
