// 插件对外暴露能力的总入口在 interface.uts ，他与Android/ios 目录下的 index.uts的关系是声明和实现的关系。


/**
 * 「1:N人脸搜索」录入人脸特征值
 * 
 * @param faceID 用户ID
 * @param callback 结果回调
 */
export type AddFaceSearchFeature = (
    faceID:string,
	addFacePerformanceMode:number,
	callback : (result : ResultJSON) => void) => void
	
	
	
/**
 * 「1:N人脸搜索」删除一张人脸照片
 * 
 * @param faceID 用户ID
 * @param callback 结果回调
 */
export type DeleteFaceSearchFeature = (
    faceID:string,
	callback : (result : ResultJSON) => void) => void


/**
 * 「1:N人脸搜索」更多个性化参数完善中
 */
export type FaceSearch = (callback: (res: ResultJSON) => void) => void


/**
 * 「1:N人脸搜索」录入一张人脸照片
 * 
 * @param faceID 用户ID
 * @param needShowConfirmDialog 是否需要显示确认框
 * @param callback 结果回调
 */

export type InsertFaceSearchFeature = (
	faceID : string,
	faceFeature : string, 
	tag : string, 
	group : string,
	callback : (result : ResultJSON) => void) => void


// ---------------------------  下面是1:1 人脸识别相关方法  ---------------------------------


//「1:1人脸识别」检测人脸是否存在
export type OnCheckFaceExist = (
    faceID: string, 
	callback: (result: ResultJSON) => void) => void

  
/**
 * 「1:1人脸识别」录入人脸信息
 * 
 * @param faceID 用户ID
 * @param needShowConfirmDialog 是否需要显示确认框
 * @param callback 结果回调
 */
export type AddFaceBySDKCamera = (
	faceID : string,
	addFacePerformanceMode:number,
	needShowConfirmDialog:boolean,
	callback : (result : ResultJSON) => void) => void




/**
 * 「1:1人脸识别」从照片中提取人脸特征
 * 
 * @param faceID 用户ID
 * @param base64FaceImage 人脸照片，Base64编码
 * @param callback 结果回调
 */
export type GetFaceFeatureByImage = (
	faceID : string,
	base64FaceImage:string,
	callback : (result : ResultJSON) => void) => void



/**
 * 「1:1人脸识别」人脸识别+活体检测
 * 
 * @param param 人脸识别参数
 * @param callback 结果回调
 */
export type FaceVerify = (
	param : FaceVerifyParam,
	callback : (result : ResultJSON) => void) => void
	
	
	
/**
 * 「1:1人脸识别」人脸识别,业务方传给FaceAISDK 插件基础参数
 */
export type FaceVerifyParam = {
  faceID: string,
  threshold: number,         // 人脸识别通过的相似度阈值 0.85到0.95
  faceLivenessType: number,  // 活体检测类型 //0 SILENT_MOTION; 1 MOTION（动作活体）; 2 SILENT（RGB图像静默活体）; 3 NONE;
  verifyTimeOut: number,     // 活体检测超时时间 秒
  motionStepSize: number,
  silentThreshold: number   
} 


/**
 * 活体检测,业务方传给FaceAISDK 插件基础参数
 */
export type LivenessParam = {
  faceLivenessType: number,         
  verifyTimeOut: number,           
  motionStepSize: number,  
  silentThreshold:number
} 
 
/**
 * 炫彩｜动作 活体检测
 * 
 * @param param 人脸识别参数
 * @param callback 结果回调
 */
export type LivenessVerify = (
	param : LivenessParam,
	callback : (result : ResultJSON) => void) => void	




/**
 * 业务方传给FaceAISDK 插件基础参数
 */
export type ResultJSON = {
  code: number,       //code 含义参考Readme 
  msg: string, 
  faceID: string,     
  faceFeature: string,  //人脸特征值
  faceBase64: string    //人脸图Base64编码
}


/**
 * 「1:1人脸识别」同步人脸特征指到SDK，比如用户换设备登陆了，把上次录入到你的业务服务器上的人脸同步就行
 * 
 * @param faceFeature 人脸特征值得长度1024.20251202新版本SDK人脸数据合规处理不在接收人脸图参数
 * @param callback 结果回调
 */
export type InsertFace = (
    faceID : string,
	faceFeature : string,
	callback : (result : ResultJSON) => void) => void



/**
 * 「1:1人脸识别」删除设备缓存的人脸信息
 * 
 * @param faceID 人脸faceID
 * @param callback 结果回调
 */
export type DeleteFaceFeature = (
    faceID : string,
	callback : (result : ResultJSON) => void) => void